### ISSUE TITLE
WoW any kind of skills unusable

### ISSUE THREAD

**Issue by xecxec** [Pulover/PuloversMacroCreator#104]
By any chance, does it prevent u in WoW from casting anything through mouse clicks or keyboard inputs after a while?

**Comment by Pulover** [comment]
No. What are you trying to do?

**Comment by xecxec** [comment]
I set up my macro and my rogue is fine. My druid keeps stuck after a while when i put it to afk and let macro do the all work. I cant click any spells on action bars or skill page not i can press anything through keyboard. When i relog, it is fixed. I couldn't figure out why this is happening.

**Comment by ozzhates** [comment]
Some games do block simulated device inputs. One way around is to define key-states ie: up & down.

**Comment by xecxec** [comment]
Yeh but it only happens on my Druid which is weird. My rogue continues to use spells freely. And i also use as you mentioned, up &down .

**Comment by Pulover** [comment]
I don't use macros in games so I don't know about rogues and druids... But @ozzhates is right, some games will block it. You can also try to change SendMode in settings to Play. It helps some times.

**Comment by ozzhates** [comment]
I don't think _PMC_ is the problem here. Maybe a game client functionality problem? Most game companies are against macros so they create whole developmental teams to countermeasure everything your trying to do. **LOL** I've never personally played(_macroed_) that game but AHK forum and Reddit were good places for that kinda help in the past. There is even a active group of people in their IRC channel.
