### ISSUE TITLE
few bugs

### ISSUE THREAD

**Issue by keklok** [Pulover/PuloversMacroCreator#109]
![bug](https://user-images.githubusercontent.com/71589796/93709245-77d53c80-fb45-11ea-8c79-569a75bdc1dd.png)
Thank you for update!
But bugs.

Sometimes
1) Message box converted to control mode. 
2) When I change the variable.The variable may not change the value the first time
3) Macros are duplicated
4) Crash and I can't open the pullover

**Comment by Pulover** [comment]
Thanks, but without the steps to reproduce them I cannot fix any of those problems.

**Comment by keklok** [comment]
it helped me 
https://github.com/Pulover/PuloversMacroCreator/issues/108#issuecomment-694816970
And
One expression was broken due to the previous version.
Thanks anyway for a great product

**Comment by Pulover** [comment]
Cool. The first issue, the one in the screenshot, I suspect you might have the Capture keystrokes option enabled, didn't you? Because I had to disable ListView refresh while at it because of crashes. So maybe something got stuck. 

I think we can close this issue for now and if you find a way to reproduce any of the problems you've described, you can open a new one, ok?

**Comment by keklok** [comment]
Enabled but I didn't record anything.

OK
