### ISSUE TITLE
That subtraction issue happen again.

### ISSUE THREAD

**Issue by chosen1ft** [Pulover/PuloversMacroCreator#132]
Greeting.

The issue happen when therre are 2 or more variables.

![22](https://user-images.githubusercontent.com/69076802/97041152-a9f11880-15a1-11eb-9619-ec725b271e92.png)
![33](https://user-images.githubusercontent.com/69076802/97041155-ab224580-15a1-11eb-9847-b4f10d245075.png)
![44](https://user-images.githubusercontent.com/69076802/97041825-b45fe200-15a2-11eb-97c8-5fd637e8aab1.png)
![55](https://user-images.githubusercontent.com/69076802/97041833-b5910f00-15a2-11eb-80be-423a43c0cc3e.png)

**Comment by Pulover** [comment]
I was trying to avoid modifying Uberi's  compile function because it's super complex, but I couldn't avoid it this time. I've removed my patch from the last time and have found and removed the bugged line from the compiler function. I just hope no other problem comes up since I have no idea what that line was supposed to do... Will be fixed in PMC for the next release.

**Comment by Pulover** [comment]
Fixed in version 5.3.1.
