### ISSUE TITLE
Could you please add the reload command?

### ISSUE THREAD

**Issue by rcsavo** [Pulover/PuloversMacroCreator#149]
In my experience the ahk scripts tend to stop working after a while and only a periodical restart seem to fix the issue. Unfortunately the reload command is not available, so I have to add it manually any time I change the macro and export the script.

Keep up your amazing work and thank you so much for making the PMC!

**Comment by Pulover** [comment]
Reload is not available because it doesn't make sense for playback. Export to ahk is just a feature, not the main purpose of pmc, so I'm not going to do this. There's a trick you can use, though. Open the Expressions window and type the command you want. For pmc it's going to be like reading an empty variable, it shouldn't do anything, but it's going to be interpreted as the command when exported.

**Comment by rcsavo** [comment]
OK, i didn't think about the built-in playback part. Other than that, typing in the command as expression seems to do the trick, so I'll stick with that solution. Thank you for taking care!
