### ISSUE TITLE
Loop Until (expression)

### ISSUE THREAD

**Issue by user3247548** [Pulover/PuloversMacroCreator#19]
I try to use Loop Until (expression).
The loop always was only executed a single time.
Expression was something like
%FrameEdgeFound%="#33333" 
I tried with and without % or "
The variable comes from a MouseGetPos inside the loop.
I now have a workaround with a If ...Break construction.

**Comment by Pulover** [comment]
In expressions you must not enclose variables in percent signs, and strings must be enclosed in quotes. Also, you must remember that the program will not clear your variables for you every time you play a macro, so if the last content of `FrameEdgeFound` was `#33333` and it's not rewritten inside the loop, it will break after the first iteration.

I have tested `Until-Loop` with this file: [UntilTest.zip](https://github.com/Pulover/PuloversMacroCreator/files/232083/UntilTest.zip), and it's working as intended, based on your description. The loop will wait until a common Open File dialog is under the mouse cursor, this is just to make sure that the "#" is not the problem since the class of that dialog is "#32770" and I could not find a control or window that starts with it to get it directly from `MouseGetPos`, but you can edit to file with the information from the window you are working on.

In the future, before opening an issue about a command functionality, please export it to an AHK script and see if it runs as expected. If the behaviors are inconsistent, then it must be an issue. Thank you.

**Comment by user3247548** [comment]
Thank you very much for creating MacroCreator and taking the time to create
the perfect example while at the same time finalizing 5.0.1
I very much like the redesign and expanded capability.
I will try out exporting an AHK script in the future.
Instead of going to Github, I could also go to the AHK forum, if I see a
problem or most likely do not do things the right way. then maybe someone
else could point me in the right direction and you can look into 5.0.x....

Are you learning German?
If you ever need a German translation, I would like to help.

What city are you living in?
I have relatives in São Paulo and visited when I was 16 years old.

**Comment by Pulover** [comment]
I know just a little bit of German. I like the language very much tried to learn it a few years ago, but couldn't find time to continue studying. I have a revision for German translation once but feel free to send me corrections for the new version, I'd appreciate it. You can use the Language editor in the settings window to make the fix and submit it to my email. Thank you.

I lived most of my life in Guarulhos, which is a city next to Sao Paulo, but last year I moved to a countryside city called Caçapava (120km from Sao Paulo). I still have relatives and friends there but I like it here, it's very calm.
