### ISSUE TITLE
Awful UI

### ISSUE THREAD

**Issue by matkoch** [Pulover/PuloversMacroCreator#33]
I don't want to be rude. I can see how this project offers a lot of features, and also required a lot of effort. But, at least from my point of view, it's a pity that the UI is such a mess. It doesn't help to learn how to use the program. Biggest issues are, that not even one "special" button is named. Secondly, there are a bunch of functions, that are totally unnecessary for normal use (like zip/unzip?).

I hope I'm not just blaming, but also productive. And I hope this helps a little for the program to become better.

**Comment by Pulover** [comment]
Hi matkoch,

Thank you for the feedback, but I have to ask you to use the forum to discuss about opinions and suggestions, please.

What you call "normal use" is relative. I cannot tell which features will be interesting to everyone and which will not. Each user will need the software for a different purpose.

I have added pre-defined toolbar layouts and ways for the user to add/remove/reorder the buttons as well as the toolbars themselves, so if you don't use a certain function, just right-click over the button and edit the toolbar. If I was to use less buttons, people would complain that some features are "hard to find".

Don't get me wrong, I always consider productive criticism and suggestions (and a lot of people have contributed to improve PMC), but you haven't really suggested anything. Just saying that the UI is such a mess doesn't contribute at all to make it better.

The program has a learning curve, but it would probably be harder for most people to learn AutoHotkey language without it. Besides, this is something I do in my spare time (even so I have stopped my other commercial projects for 4 months to work on the last update), and still I took the time to write a help file, make video tutorials, examples and added a very efficient command/function search system.

I did the best I could with what AHK could offer (you may not know but I have written the classes to work with toolbars and rebars myself, and it's not that simple to add labels to just some of the buttons), so those resources will have to be enough to get started, because I'm absolutely not going to rewrite the UI.

**Comment by matkoch** [comment]
> Don't get me wrong, I always consider productive criticism and suggestions (and a lot of people have contributed to improve PMC), but you haven't really suggested anything. Just saying that the UI is such a mess doesn't contribute at all to make it better.

I did. I said the biggest issue (for me), is that the toolbar buttons just have symbols, and no text. Actually, for me it's the other way around. I'm more likely to dig into AHK because of that.

Like I said, I appreciate your work on that. My intentions were only good.

**Comment by Pulover** [comment]
> I did. I said the biggest issue (for me), is that the toolbar buttons just have symbols, and no text.

Well, that's a common UI in many applications, such as Notepad++ and FileZilla, for example. That's why I also add the **menubar** with all shortcuts from the toolbars, so the user can find the commands and features by name as well. You could hide all toolbars and still find all shortcuts on the main window.

I didn't say that your intentions were not good, or that my program is the best way to learn AHK. I just wanted to create a good automation tool that was free for everyone, and at the same time could help **some** people to learn about AHK language. And I don't think the UI is just "awful".

**Comment by matkoch** [comment]
Ok, changed heading, didn't want to hurt feelings :)

**Comment by wcrlewis** [comment]
This is closed, I would like to iterate slightly if I may.  I used this software around two years ago and it was very easy to accomplish some great tasks.  There are so many features now it was difficult to find what I intended to do.  The problem is that the buttons do not have tooltips, the small text windows that pop up and explain a button when you hover your mouse over it.  With a bit of added explanation, everything would benefit greatly.  Thank you for your great software.

**Comment by Pulover** [comment]
> The problem is that the buttons do not have tooltips
ALL buttons have tooltips.
![captura de tela 2016-07-26 14 32 56](https://cloud.githubusercontent.com/assets/4416483/17148583/26cdbe4c-533e-11e6-8d6a-59de767cf705.png)
> With a bit of added explanation, everything would benefit greatly.
I did write a help file...

**Comment by wcrlewis** [comment]
I see that now. Must have been the system, sorry about that.  I sent a separate contact about the F12/IE function not working and maybe that is the computer too.  I appreciate your response, my apologies for bothering.  To the OP, maybe you just want to turn off all the button toolbars?
