### ISSUE TITLE
Webpage tutorials down. Forum registration down too. And lets not talk discord.

### ISSUE THREAD

**Issue by nightmaredream** [Pulover/PuloversMacroCreator#82]
It's difficult to find complete and organized information about Pulover Macro Creator online

**Comment by tmplese** [comment]
Hi!!

There is a command called "Text"... It looks like a blue "T" on the command
buttons and this will input the complete text instead of the keystrokes.

Additionaly:
- this command allows you to send as text whatever you have on the
clipboard (there is an option for that)
- you can create a variable (in the "variables" button) and then recall it
from the text command also


I aggree! There is minor documentation on PMC, you gotta be patient... what
you ask tells me you just started using it and there is a lot to make use
of. Try checking the videos on the PMC website, they are looong and dense
but with substance.

**Comment by nightmaredream** [comment]
Okay so i click the T and enter the text i need to input, hence, a convert file X to file Y command, at whole, how do i insert a loop to increase the number until 3k? I can still use notepad++

**Comment by tmplese** [comment]
There is also an object for loop (green button with a cycle arrow inside)... It'll insert 2 lines (start and end of loop) so whatever it goes inside the loop will be repeated. The loop parameter is the amount of rep's (3k)

Now, if you want to increase a certain value on each loop, you'll have to create a new variable before the loop and set it to 0,  then increase it using a function (other button) on each loop (something like "var=0", then Loop, then "var=var+1")

**Comment by nightmaredream** [comment]
Awesome tho i'm unsure how to use var so i read AHK documentation about it. 
I used macro softwares in the past but Pu is really nice and it's AHK so it's really standard. 
Tho i wonder, can i use, instead of filesnames from 0000 to 3000, a more complicated file list?
Say, i had to rename the files in a series of same-prefix names but it removes the files's original names. 
Doing that to facilitate the conversion of files.
But could i make a Pu script that uses a file list to name variables at every loops instead of giving number value?
For example, alphabetical order> Azramatata.filetypeA is processed first, and the script gets the filename from the folder it'S conttained, and it gives the same name to the variable for "current instance of the loop"...Then next loop it gets filename for the next alphabetical order file...
It would allow me to keep filenames which would really give me a clue about classifying the files afterward.
For the moment, i'll try to figure out how to work with My First Variable.

**Comment by tmplese** [comment]
In those cases, what I do is to ise an excel file to help me... Use the
command "window" (blue one) and take "Win Activate" to switch between excel
and the file explorer and loop that.

Excel: You can get the list of all the 3000 file names in excel by going to
Data>Get Data>From Folder.... And then import. This will give you the list
of filenames, make sure is in alphabetical order and = to the file explorer
order. Then you can put the new name in front of the imported ones to make
your base for the robot.

Back to PMC:

Something like:

1. Start loop (until 3000)
2. Activate excel
3. Copy (Ctrl+C)
Optional: variable=%clipboard%
4. Activate file explorer
5. F2, Ctrl+V, enter, next line
Optional: Instead of Ctrl+V: Text command with %variable%
6. Activate excel
7. Next line
8. End loop (start over)

On step 5 there may be a trick.... Maybe when you change the name, the file
explorer will re-arrange the files, think on the names so that it won't
bother you.
