### ISSUE TITLE
Dual Screen recording seems to confuse Pu

### ISSUE THREAD

**Issue by nightmaredream** [Pulover/PuloversMacroCreator#84]
When i record on left screen, once done and once i play it back, it acts as if both screens counted as one, and every actions are done twice as large. I'll turn off second monitor for the moment.

**Comment by tmplese** [comment]
2 screens = trouble. Just avoid it if you are using anything that depends on screen coordinates like Clicks And Image Search. Also, if you do a program and then want to use it on other computer, make sure they have tye same screen resolution. If not, you'll have to recalibrate all the actions that depend on coordinates.

I only go with recording for "quick and dirty" stuff, doing command by command is much manageable and optimizable

**Comment by nightmaredream** [comment]
I would really like to learn the art of Pu/AHK. 
What i did there was to batch mix 300 images with 4 separate layers per image in 4 separate folders and merged in one file for each. Adjusting layers and stuff. With my favorite image editor.
I hade to use tinytask because recording even with a single screen with Pu resulted into really incorrect actions, and it's REALLY difficult to stop once it started. There's no panic button :x 

Tho, are there securities possible? 

Like "if error pop up appears, stop" 

"If workspace change, stop"

"If this window AND this window gets covered, stop"

?

**Comment by tmplese** [comment]
Hi,

Stop Button: F8
Yes, you can do "if xxxx then YYY" or wait until window appears or this kind of stuff.

I'd recommend you hover over all the action icons and see what they do since it is quite self-explanatory.  Open the settings button to learn some tweaks and stuff you can do and also see the videos on the PMC website (long and boring but with lots of stuff).

![PMC Navigation](https://user-images.githubusercontent.com/49514543/69017254-0ae19b00-09a6-11ea-8e0e-1a36e8226cec.png)

**Comment by tmplese** [comment]
And please don't record anymore 🤣🤣🤣. Go command by command.... it is way better

**Comment by Pulover** [comment]
Thanks for all the help @tmplese  :)
